name: Build Multi-Platform Installer

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest 

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            node_version: '18'
          - os: windows-latest
            node_version: '18'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Set up Wine
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y wine64 wine32

      - name: Setup Node.js
        uses: actions/setup-node@v4 
        with:
          node-version: ${{ matrix.node_version }}
        
      - name: Install dependencies
        run: npm install --legacy-peer-deps
        
      - name: Set up GitHub Token
        run: echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV

      - name: Debug GH_TOKEN
        run: echo "GH_TOKEN is set"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build Windows Installer
        if: matrix.os == 'windows-latest'
        run: npm run build:win
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build Linux Installer
        if: matrix.os == 'ubuntu-latest'
        run: npm run build:linux
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      # Upload Artifacts based on OS
      - name: Upload Windows Build Artifact
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4  
        with:
          name: windows-installer
          path: dist/*.exe
          compression-level: 0  

      - name: Upload Linux Build Artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4  
        with:
          name: linux-installer
          path: dist/*.AppImage
          compression-level: 0

      # Create GitHub Release (with artifacts)
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: "Release notes for the new build"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}


      - name: Upload Release Asset (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/*.exe
          asset_name: WordloudApp-1.0.0.exe
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload Release Asset (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/*.AppImage
          asset_name: WordloudApp-1.0.0.AppImage
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
