name: Build Windows Installer

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  tags:
    - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Windows Installer
        run: npm run build:win

      - name: Upload Windows Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-installer
          path: dist/*.exe
